
# Generated by CodiumAI
from harolds_hotdogs_class_6 import HaroldsHotdogs


import pytest


class TestHaroldsHotdogs:

    # Add items to cart with valid input
    def test_add_to_cart_valid_input(self):
        hotdogs = HaroldsHotdogs()
        hotdogs.add_to_cart(1, 2)
        assert hotdogs.cart == [2, 0, 0, 0]

    # Display menu with valid input
    def test_display_menu_valid_input(self):
        hotdogs = HaroldsHotdogs()
        menu = hotdogs.display_menu()
        expected_menu = "(1) Hot Dog 7.50\n(2) Crisps 1.00\n(3) Soda 1.50\n(4) Gourmet Ketchup 10.00\n"
        assert menu == expected_menu

    # Calculate total with valid input
    def test_calculate_total_valid_input(self):
        hotdogs = HaroldsHotdogs()
        hotdogs.add_to_cart(1, 2)
        hotdogs.add_to_cart(2, 3)
        hotdogs.add_to_cart(3, 1)
        hotdogs.calculate_total()
        assert hotdogs.total == 20.50

    # Add items to cart with invalid input
    def test_add_to_cart_invalid_input(self):
        hotdogs = HaroldsHotdogs()
        hotdogs.add_to_cart(5, 2)
        assert hotdogs.cart == [0, 0, 0, 0]

    # Display menu with empty menu
    def test_display_menu_empty_menu(self):
        hotdogs = HaroldsHotdogs()
        hotdogs.menu_items = []
        hotdogs.menu_prices = []
        menu = hotdogs.display_menu()
        assert menu == ""

    # Calculate total with empty cart
    def test_calculate_total_empty_cart(self):
        hotdogs = HaroldsHotdogs()
        hotdogs.calculate_total()
        assert hotdogs.total == 0.0
